export type Lang = 'en' | 'fr';

const copy = {
  en: {
    jobs:'Jobs', newJob:'New job', editJob:'Edit job', import:'Import', settings:'Settings', logout:'Log out', local:'This instance', instances:'Instances',
    search:'Search jobs…', all:'All', sync:'Sync', commands:'Commands', cron:'Cron', watch:'Watch', manual:'Manual', disabled:'Disabled',
    run:'Run now', dry:'Dry-run', stop:'Stop', history:'History', edit:'Edit', clone:'Clone', disable:'Disable', enable:'Enable', delete:'Delete',
    empty:'No jobs yet', emptyHint:'Create a job or import an existing host trigger.', review:'Review required', running:'Running', queued:'Queued', idle:'Idle',
    save:'Save', retry:'Retry', saving:'Saving…', saveJob:'Save job', cancel:'Cancel', close:'Close', refresh:'Refresh', loading:'Loading…', none:'None', noHistory:'No persisted runs yet.',
    systemImport:'System inventory & import', systemTrash:'System trash', notifications:'Notifications', remoteInstances:'Remote instances',
    name:'Name', jobType:'Job type', synchronization:'Synchronization', syncDesc:'Copy A → B with rsync or rclone.', command:'Command', commandDesc:'Run a shell command on the host.',
    script:'Script', scriptDesc:'Execute a canonical script path without shell parsing.', commandToRun:'Command', commandHint:'Executed on the host with captured stdout/stderr.', scriptPath:'Script path', arguments:'Arguments',
    executionOwnership:'Execution ownership', syncbridgeBackend:'SyncBridge', syncbridgeBackendDesc:'Live logs, stop control and overlap protection.', systemBackend:'System', systemBackendDesc:'Persistent host cron/systemd trigger that survives container downtime.',
    hostIdentity:'Host execution identity', scriptOwner:'Script owner', fixedIdentity:'Fixed identity', user:'User', uid:'UID', group:'Group', gid:'GID',
    folders:'Folders', sourceA:'Source (A)', destinationB:'Destination (B)', choose:'Choose', browse:'Browse',
    copyBehavior:'Copy behavior', accumulation:'Accumulation', accumulationDesc:'Add/update files; never delete in B.', exactMirror:'Exact mirror', exactMirrorDesc:'B becomes identical to A; deletions propagate.', move:'Move', moveDesc:'Copy into B then remove source files.',
    engine:'Engine', compare:'Compare', trigger:'Trigger', manualDesc:'Only runs when requested.', scheduled:'Scheduled', scheduledDesc:'Runs on a cron expression.', watchDesc:'Debounced filesystem watch with polling fallback.',
    folderToWatch:'Folder to watch', filePatterns:'File patterns', watchMode:'Watch mode', debounce:'Debounce (s)', pollInterval:'Poll interval (s)',
    advanced:'Advanced safety & execution', timeout:'Timeout (s)', stopGrace:'Stop grace (s)', overlap:'Overlap', umask:'Umask', environment:'Environment', bandwidth:'Bandwidth limit', exclude:'Exclude', maxDelete:'Max delete', backupKeep:'Backup keep',
    backupChanged:'backup changed/deleted files', skipNewer:'skip newer destination files', systemBackup:'system backup metadata',
    addInstance:'Add instance', url:'URL', password:'Password', noRemote:'No remote instance configured.', remoteHint:'Credentials are stored encrypted by the local SyncBridge instance; connection is tested before saving.', testing:'Testing…',
    notificationUrl:'Notification URL', notificationHint:'SyncBridge sends a plain-text POST with a Title header; natively compatible with ntfy.', notifySuccess:'Notify successful runs too', failuresOnly:'Off = failures only.', test:'Test',
    scanningHost:'Scanning host…', nothingDetected:'Nothing detected', nothingDetectedHint:'No cron, systemd or importable sync command was found.', trash:'Trash', trashEmpty:'Trash is empty', backToScan:'Back to scan', restore:'Restore', notRestorable:'not restorable',
    selected:'selected', deleteSelected:'Delete selected', yourTriggers:'Your triggers', yourTriggersSub:'scripts, cron, inotify, sync commands', systemTriggers:'System triggers', systemTriggersSub:'OS & packages', systemWarning:'These entries are maintained by the operating system or packages. Modifying them may break maintenance, updates or cleanup jobs.',
    alreadyManaged:'already managed by SyncBridge', select:'select', inspectImport:'Import (inspect)', importAsSync:'Import as sync', reenableHost:'Re-enable host trigger', disableHost:'Disable host trigger', stopProcess:'Stop process (SIGTERM)', commandNotExtracted:'command not extracted',
    remoteRemoved:'Remote removed — back to local instance', pilotingRemote:'Piloting remote instance', localInstance:'Local instance', dryStarted:'Dry-run started', runStarted:'Run started', stopRequested:'Stop requested', disabledCopy:'Disabled copy created', jobUpdated:'Job updated', jobCreated:'Job created', jobDeleted:'Job deleted', jobEnabled:'Job enabled', jobDisabled:'Job disabled',
    stopConfirm:'Stop this active run? Files already copied remain in place.', deleteConfirm:'Delete this job?', removeRemoteConfirm:'Remove this remote from SyncBridge? The remote itself is not modified.',
    fieldNameRequired:'Name is required', fieldPathsRequired:'Source and destination are required', fieldCommandRequired:'Command is required', fieldScriptAbsolute:'Script path must be absolute', fieldWatchSourceRequired:'A watch folder is required', fieldSystemTrigger:'System scheduling requires cron or watch',
    testSent:'Test notification sent.', settingsSaved:'Settings saved.',
    authTitle:'Sign in', authCreate:'Create your account', authLead:'Authenticate to manage host automations.', authCreateLead:'First start: create the administrator account protecting host execution.', authUsername:'Username', authPassword:'Password', authConfirm:'Confirm password', authSignIn:'Sign in', authCreateButton:'Create account', authManaged:'Account managed through SYNCBRIDGE_USER / SYNCBRIDGE_PASSWORD.', authUserShort:'Username must contain at least 3 characters.', authPassShort:'Password must contain at least 6 characters.', authMismatch:'Passwords do not match.'
  },
  fr: {
    jobs:'Jobs', newJob:'Nouveau job', editJob:'Éditer le job', import:'Importer', settings:'Réglages', logout:'Déconnexion', local:'Cette instance', instances:'Instances',
    search:'Rechercher des jobs…', all:'Tous', sync:'Sync', commands:'Commandes', cron:'Cron', watch:'Surveillance', manual:'Manuel', disabled:'Désactivés',
    run:'Lancer', dry:'Simuler', stop:'Arrêter', history:'Historique', edit:'Éditer', clone:'Cloner', disable:'Désactiver', enable:'Réactiver', delete:'Supprimer',
    empty:'Aucun job', emptyHint:'Crée un job ou importe un déclencheur existant de l’hôte.', review:'À vérifier', running:'En cours', queued:'En attente', idle:'Inactif',
    save:'Enregistrer', retry:'Réessayer', saving:'Enregistrement…', saveJob:'Enregistrer le job', cancel:'Annuler', close:'Fermer', refresh:'Actualiser', loading:'Chargement…', none:'Aucun', noHistory:'Aucun run persistant pour le moment.',
    systemImport:'Inventaire système & import', systemTrash:'Corbeille système', notifications:'Notifications', remoteInstances:'Instances distantes',
    name:'Nom', jobType:'Type de job', synchronization:'Synchronisation', syncDesc:'Copie A → B avec rsync ou rclone.', command:'Commande', commandDesc:'Lance une commande shell sur l’hôte.',
    script:'Script', scriptDesc:'Exécute un chemin de script canonique sans parsing shell.', commandToRun:'Commande à exécuter', commandHint:'Exécutée sur l’hôte avec stdout/stderr capturés.', scriptPath:'Chemin du script', arguments:'Arguments',
    executionOwnership:'Exécution', syncbridgeBackend:'SyncBridge', syncbridgeBackendDesc:'Logs en direct, arrêt et protection anti-chevauchement.', systemBackend:'Système', systemBackendDesc:'Vrai déclencheur cron/systemd hôte qui survit à l’arrêt du conteneur.',
    hostIdentity:'Identité d’exécution sur l’hôte', scriptOwner:'Propriétaire du script', fixedIdentity:'Identité fixe', user:'Utilisateur', uid:'UID', group:'Groupe', gid:'GID',
    folders:'Dossiers', sourceA:'Source (A)', destinationB:'Destination (B)', choose:'Choisir', browse:'Parcourir',
    copyBehavior:'Comportement de copie', accumulation:'Accumulation', accumulationDesc:'Ajoute/met à jour ; ne supprime jamais dans B.', exactMirror:'Miroir exact', exactMirrorDesc:'B devient identique à A ; les suppressions sont propagées.', move:'Déplacement', moveDesc:'Copie dans B puis retire les fichiers de la source.',
    engine:'Moteur', compare:'Comparaison', trigger:'Déclencheur', manualDesc:'Se lance uniquement à la demande.', scheduled:'Planifié', scheduledDesc:'Se lance selon une expression cron.', watchDesc:'Surveillance avec anti-rebond et scan de secours.',
    folderToWatch:'Dossier à surveiller', filePatterns:'Filtres de fichiers', watchMode:'Mode de surveillance', debounce:'Anti-rebond (s)', pollInterval:'Intervalle de scan (s)',
    advanced:'Options avancées — sécurité & exécution', timeout:'Délai max (s)', stopGrace:'Délai avant kill (s)', overlap:'Chevauchement', umask:'Umask', environment:'Environnement', bandwidth:'Limite de débit', exclude:'Exclusions', maxDelete:'Garde-fou suppressions', backupKeep:'Versions à conserver',
    backupChanged:'corbeille des fichiers modifiés/supprimés', skipNewer:'ne pas écraser les fichiers plus récents en destination', systemBackup:'métadonnées de sauvegarde système',
    addInstance:'Ajouter une instance', url:'URL', password:'Mot de passe', noRemote:'Aucune instance distante configurée.', remoteHint:'Les identifiants sont chiffrés par l’instance SyncBridge locale ; la connexion est testée avant l’enregistrement.', testing:'Test…',
    notificationUrl:'URL de notification', notificationHint:'SyncBridge envoie un POST texte avec un header Title ; compatible nativement avec ntfy.', notifySuccess:'Notifier aussi les succès', failuresOnly:'Désactivé = échecs uniquement.', test:'Tester',
    scanningHost:'Scan de l’hôte…', nothingDetected:'Rien détecté', nothingDetectedHint:'Aucun cron, systemd ou commande de synchro importable trouvé.', trash:'Corbeille', trashEmpty:'Corbeille vide', backToScan:'Retour au scan', restore:'Restaurer', notRestorable:'non restaurable',
    selected:'sélectionné(s)', deleteSelected:'Supprimer la sélection', yourTriggers:'Tes déclencheurs', yourTriggersSub:'scripts, cron, inotify, commandes de synchro', systemTriggers:'Déclencheurs système', systemTriggersSub:'OS & paquets', systemWarning:'Ces entrées sont maintenues par le système ou les paquets. Les modifier peut casser la maintenance, les mises à jour ou le nettoyage.',
    alreadyManaged:'déjà géré par SyncBridge', select:'sél.', inspectImport:'Importer (visualiser)', importAsSync:'Importer comme synchro', reenableHost:'Réactiver sur l’hôte', disableHost:'Désactiver sur l’hôte', stopProcess:'Arrêter le process (SIGTERM)', commandNotExtracted:'commande non extraite',
    remoteRemoved:'Instance retirée — retour à l’instance locale', pilotingRemote:'Pilotage de l’instance distante', localInstance:'Instance locale', dryStarted:'Simulation lancée', runStarted:'Run lancé', stopRequested:'Arrêt demandé', disabledCopy:'Copie créée désactivée', jobUpdated:'Job modifié', jobCreated:'Job créé', jobDeleted:'Job supprimé', jobEnabled:'Job réactivé', jobDisabled:'Job désactivé',
    stopConfirm:'Arrêter ce run actif ? Les fichiers déjà copiés restent en place.', deleteConfirm:'Supprimer ce job ?', removeRemoteConfirm:'Retirer cette instance de SyncBridge ? L’instance distante elle-même ne sera pas modifiée.',
    fieldNameRequired:'Nom requis', fieldPathsRequired:'Source et destination requises', fieldCommandRequired:'Renseigne la commande à exécuter', fieldScriptAbsolute:'Le chemin du script doit être absolu', fieldWatchSourceRequired:'Un dossier à surveiller est requis', fieldSystemTrigger:'Le backend système nécessite un cron ou une surveillance',
    testSent:'Notification de test envoyée.', settingsSaved:'Réglages enregistrés.',
    authTitle:'Connexion', authCreate:'Créer ton compte', authLead:'Connecte-toi pour gérer les automatisations de l’hôte.', authCreateLead:'Premier lancement : crée le compte administrateur qui protège l’exécution sur l’hôte.', authUsername:'Identifiant', authPassword:'Mot de passe', authConfirm:'Confirme le mot de passe', authSignIn:'Se connecter', authCreateButton:'Créer le compte', authManaged:'Compte géré par SYNCBRIDGE_USER / SYNCBRIDGE_PASSWORD.', authUserShort:'Identifiant : 3 caractères minimum.', authPassShort:'Mot de passe : 6 caractères minimum.', authMismatch:'Les deux mots de passe ne correspondent pas.'
  }
} as const;

export type CopyKey = keyof typeof copy.en;
export const tr = (lang: Lang, key: CopyKey) => copy[lang][key];
