<script lang="ts">
  import type { ApiClient } from '../api/client';
  import { importScan, systemDelete, systemRestore, systemScan, systemToggle, systemTrash } from '../api/syncbridge';
  import { newJobForm, type JobForm } from '../domain/jobs';
  import type { ImportFound, SystemItem, TrashEntry } from '../domain/types';
  import { tr, type Lang } from '../i18n';
  export let client: ApiClient;
  export let lang: Lang = 'en';
  export let onImport: (form: JobForm) => void = () => {};
  export let onClose: () => void = () => {};
  let items:SystemItem[]=[], found:ImportFound[]=[], trash:TrashEntry[]=[], busy=true, error='', trashMode=false;
  let selected=new Set<number>();
  $: custom=items.filter(x=>x.class!=='system');
  $: system=items.filter(x=>x.class==='system');
  async function scan(){busy=true;error='';trashMode=false;selected=new Set();try{const [s,i]=await Promise.all([systemScan(client),importScan(client)]);items=s.items??[];found=i.found??[];}catch(e){error=e instanceof Error?e.message:String(e)}finally{busy=false}}
  async function showTrash(){busy=true;error='';try{trash=await systemTrash(client);trashMode=true;}catch(e){error=e instanceof Error?e.message:String(e)}finally{busy=false}}
  async function toggle(item:SystemItem){const killing=item.type==='inotify-proc';const message=killing?(lang==='fr'?'Arrêter ce process inotify vivant avec SIGTERM ? Ce n’est pas réversible ; il peut redémarrer avec son service parent.':'Stop this live inotify process with SIGTERM? This is not reversible; it may restart with its parent service.'):(item.disabled?tr(lang,'reenableHost'):tr(lang,'disableHost')); if(!confirm(message))return;try{await systemToggle(client,item);await scan()}catch(e){error=e instanceof Error?e.message:String(e)}}
  async function remove(list:SystemItem[]){if(!list.length)return;const answer=prompt(lang==='fr'?`Supprimer ${list.length} déclencheur(s) de l’hôte ? Une copie récupérable sera placée dans la corbeille SyncBridge. Tape delete pour confirmer.`:`Delete ${list.length} host trigger(s)? A recoverable copy is placed in SyncBridge trash. Type delete to confirm.`);if((answer??'').trim().toLowerCase()!=='delete')return;try{await systemDelete(client,list);await scan()}catch(e){error=e instanceof Error?e.message:String(e)}}
  async function restore(item:TrashEntry){try{await systemRestore(client,[item]);await showTrash()}catch(e){error=e instanceof Error?e.message:String(e)}}
  function select(index:number,checked:boolean){const next=new Set(selected);checked?next.add(index):next.delete(index);selected=next}
  function importSystem(item:SystemItem){const f=newJobForm();f.name=item.name||`Import ${item.type}`;f.enabled=false;f.action={type:'command',command:item.target||''};if(item.type==='cron'&&item.schedule.trim().split(/\s+/).length===5){f.trigger='cron';f.cron=item.schedule}else if(item.type==='systemd-path'||item.type==='inotify-proc'){f.trigger='watch';f.source=item.schedule}else f.trigger='manual';onImport(f)}
  function importFound(item:ImportFound){const f=newJobForm();f.name=`Import ${item.source.split('/').filter(Boolean).pop()||'sync'}`;f.enabled=false;if(f.action.type==='sync'&&f.action.sync){f.action.sync.engine=item.engine==='rclone'?'rclone':'rsync';f.action.sync.source=item.source.replace(/\/$/,'');f.action.sync.dest=item.dest.replace(/\/$/,'');f.action.sync.mode=/--delete/.test(item.line)||item.verb==='sync'?'mirror':item.verb==='move'?'move':'add'}if(item.cron){f.trigger='cron';f.cron=item.cron}onImport(f)}
  scan();
</script>
<div class="scrim open" role="presentation" on:click|self={onClose}><section class="modal" role="dialog" aria-modal="true">
<header class="modal-h"><h2>{trashMode?tr(lang,'systemTrash'):tr(lang,'systemImport')}</h2><span class="flex"></span>{#if !trashMode}<button class="btn ghost sm" on:click={showTrash}>{tr(lang,'trash')}</button>{/if}<button class="btn ghost sm icon-btn" on:click={onClose}>✕</button></header>
<div class="modal-b">{#if error}<div class="error-banner">{error}</div>{/if}{#if busy}<div class="hint">{tr(lang,'scanningHost')}</div>{:else if trashMode}<button class="btn sm ghost" on:click={scan}>← {tr(lang,'backToScan')}</button>{#if !trash.length}<div class="empty" style="padding:24px;margin-top:14px"><b>{tr(lang,'trashEmpty')}</b></div>{/if}{#each trash as item}<div class="imp-item"><div class="imp-flow"><span class="imp-eng">{item.type}</span><span class="p">{item.name||item.target}</span>{#if item.schedule}<span class="p">{item.schedule}</span>{/if}</div><div class="imp-meta"><span>{item.ts}</span><span class="imp-file">{item.file}</span></div><div class="imp-actions">{#if item.restorable}<button class="btn sm pri" on:click={()=>restore(item)}>{tr(lang,'restore')}</button>{:else}<span class="hint">{tr(lang,'notRestorable')}</span>{/if}</div></div>{/each}{:else}
{#if selected.size}<div class="info-banner inline-actions"><b>{selected.size} {tr(lang,'selected')}</b><button class="btn sm dgr" on:click={()=>remove([...selected].map(i=>items[i]).filter(Boolean))}>{tr(lang,'deleteSelected')}</button></div>{/if}
{#if !items.length&&!found.length}<div class="empty" style="padding:32px"><b>{tr(lang,'nothingDetected')}</b><p>{tr(lang,'nothingDetectedHint')}</p></div>{/if}
{#if custom.length||found.length}<div class="section-h">{tr(lang,'yourTriggers')} <span class="sh-sub">— {tr(lang,'yourTriggersSub')}</span></div>{#each custom as item}<div class="imp-item"><div class="imp-flow"><span class="imp-eng">{item.type}</span><span class="p">{item.name}</span>{#if item.schedule}<span class="p">{item.schedule}</span>{/if}{#if item.disabled}<span class="off-lbl">{tr(lang,'disabled')}</span>{/if}</div><div class="imp-meta"><span>→ <b>{item.target||tr(lang,'commandNotExtracted')}</b></span><span class="imp-file">{item.file}</span></div>{#if item.managed}<div class="imp-warn good">✓ {tr(lang,'alreadyManaged')}</div>{/if}<div class="imp-actions"><label class="imp-sel"><input type="checkbox" checked={selected.has(items.indexOf(item))} on:change={(e)=>select(items.indexOf(item),(e.currentTarget as HTMLInputElement).checked)}> {tr(lang,'select')}</label><button class="btn sm pri" on:click={()=>importSystem(item)}>{tr(lang,'import')}</button>{#if !item.managed}<button class="btn sm" on:click={()=>toggle(item)}>{item.type==='inotify-proc'?tr(lang,'stopProcess'):item.disabled?tr(lang,'reenableHost'):tr(lang,'disableHost')}</button>{/if}<button class="btn sm dgr" on:click={()=>remove([item])}>{tr(lang,'delete')}</button></div></div>{/each}
{#each found as item}<div class:warn={!item.local} class="imp-item"><div class="imp-flow"><span class="imp-eng">{item.engine} {item.verb}</span><span class="p">{item.source}</span><span class="arrow">→</span><span class="p">{item.dest}</span></div><div class="imp-meta">{#if item.cron}<span>cron: <b>{item.cron}</b></span>{/if}<span class="imp-file">{item.file}</span></div>{#if item.warning}<div class="imp-warn">⚠ {item.warning}</div>{/if}<div class="imp-actions"><button class="btn sm pri" on:click={()=>importFound(item)}>{tr(lang,'importAsSync')}</button></div></div>{/each}{/if}
{#if system.length}<div class="section-h" style="margin-top:24px">{tr(lang,'systemTriggers')} <span class="sh-sub">— {tr(lang,'systemTriggersSub')}</span></div><div class="sys-warn">⚠ {tr(lang,'systemWarning')}</div>{#each system as item}<div class="imp-item sys"><div class="imp-flow"><span class="imp-eng">{item.type}</span><span class="p">{item.name}</span>{#if item.schedule}<span class="p">{item.schedule}</span>{/if}</div><div class="imp-meta"><span>→ <b>{item.target}</b></span><span class="imp-file">{item.file}</span></div><div class="imp-actions"><button class="btn sm" on:click={()=>importSystem(item)}>{tr(lang,'inspectImport')}</button><button class="btn sm" on:click={()=>toggle(item)}>{item.type==='inotify-proc'?tr(lang,'stopProcess'):item.disabled?tr(lang,'reenableHost'):tr(lang,'disableHost')}</button><button class="btn sm dgr" on:click={()=>remove([item])}>{tr(lang,'delete')}</button></div></div>{/each}{/if}
{/if}</div>
<footer class="modal-f"><button class="btn ghost" on:click={onClose}>{tr(lang,'close')}</button>{#if !trashMode}<button class="btn" on:click={scan}>{tr(lang,'refresh')}</button>{/if}</footer>
</section></div>
